name: zoneminder
base: core18
version: 'master'
summary: video camera security and surveillance solution
description: |
  ZoneMinder is intended for use in single or multi-camera video security
  applications, including commercial or home CCTV, theft prevention and child
  or family member or home monitoring and other care scenarios. It
  supports capture, analysis, recording, and monitoring of video data coming
  from one or more video or network cameras attached to a Linux system.
  ZoneMinder also support web and semi-automatic control of Pan/Tilt/Zoom
  cameras using a variety of protocols. It is suitable for use as a home
  video security system and for commercial or professional video security
  and surveillance. It can also be integrated into a home automation system
  via X.10 or other protocols.

grade: devel
confinement: devmode

parts:
  zoneminder:
    build-packages:
      - g++
      - libx264-dev
      - libmp4v2-dev
      - libavdevice-dev
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libswresample-dev
      - libswscale-dev
      - libbz2-dev
      - libgcrypt11-dev
      - libcurl4-gnutls-dev
      - libturbojpeg0-dev
      - default-libmysqlclient-dev
      - libpcre3-dev
      - libpolkit-gobject-1-dev
      - libv4l-dev
      - libvlc-dev
      - libdate-manip-perl
      - libdbd-mysql-perl
      - libphp-serialization-perl
      - libsys-mmap-perl
      - libwww-perl
      - libdata-uuid-perl
      - libssl-dev
      - libcrypt-eksblowfish-perl
      - libdata-entropy-perl
    stage-packages:
      - ffmpeg
      - net-tools
      - apache2
      - libcurl3-gnutls
      - libmp4v2-2
      - libmysqlclient20
      - libpsl5
      - librtmp1
      - libslang2
      - libvlc5
      - libvlccore9
      - libglu1-mesa
      - freeglut3
      - mysql-server
      - libapache2-mod-php
    source: git://github.com/ZoneMinder/zoneminder
    plugin: cmake
    source-type: git
    configflags:
      - "-DCMAKE_SKIP_RPATH=ON"
      - "-DCMAKE_VERBOSE_MAKEFILE=OFF"
      - "-DCMAKE_COLOR_MAKEFILE=OFF"
      - "-DZM_RUNDIR=/var/run/zm"
      - "-DZM_SOCKDIR=/var/run/zm"
      - "-DZM_TMPDIR=/var/tmp/zm"
      - "-DZM_LOGDIR=/var/log/zm"
      - "-DZM_WEBDIR=/usr/share/zoneminder/www"
      - "-DZM_CONTENTDIR=/var/cache/zoneminder"
      - "-DZM_CACHEDIR=/var/cache/zoneminder/cache"
      - "-DZM_CGIDIR=/usr/lib/zoneminder/cgi-bin"
      - "-DZM_WEB_USER=www-data"
      - "-DZM_WEB_GROUP=www-data"
      - "-DZM_DB_HOST=localhost:unix_socket"
      - "-DCMAKE_INSTALL_SYSCONFDIR=etc/zm"
      - "-DZM_CONFIG_DIR=/etc/zm"
      - "-DCMAKE_BUILD_TYPE=Debug"
# MySQL
  mysql-server:
    plugin: dump
    source: ./snap-wrappers/mysql
    stage-packages:
      - mysql-server
      - mysql-client
    organize:
      mysql-start-server: bin/mysql-start-server
      mysql-start-client: bin/mysql-start-client
apps:
# Apache daemon
  apache:
    command: apache2ctl -k start -DFOREGROUND
    stop-command: apache2ctl -k stop
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind, removable-media]

# MySQL
  mysqld:
    command: mysql-start-server
    daemon: simple
#    plugs:
#      - process-control
#      - network
#      - network-bind
  mysql:
    command: mysql-start-client
#    plugs:
#      - process-control
#      - network

  zoneminder:
    command: zmpkg.pl start
    daemon: forking
    plugs: [network,network-bind]
    restart-condition: always
    restart-delay: 10s
