#!/bin/sh -e

. /etc/zm/zm.conf

/usr/sbin/a2enconf zoneminder
/usr/sbin/a2enmod cgi
/usr/sbin/a2enmod rewrite
/usr/sbin/a2enmod headers
/usr/sbin/a2enmod expires

MYSQL_CONF_DIR="${MYSQL_SNAPDIR}/etc/mysql"
MYSQL_CONF_FILE="${CONFDIR}/my.cnf"

#snapctl start mysql-server
#if ! $(echo quit | mysql --defaults-file=$MYSQL_CONF_FILE zm > /dev/null 2> /dev/null) ; then
  echo "Creating zm db"
  cat /usr/share/zoneminder/db/zm_create.sql | /usr/bin/mysql --defaults-file=$MYSQL_CONF_FILE
  if [ $? -ne 0 ]; then
    echo "Error creating db."
    exit 1;
  fi
  ## This creates the user.
  echo "GRANT LOCK tables,alter,drop,select,insert,update,delete,create,index,alter routine,create routine,trigger,execute on ${ZM_DB_NAME}.* to '${ZM_DB_USER}'@localhost identified by \"${ZM_DB_PASS}\";" | /usr/bin/mysql --defaults-file=$MYSQL_CONF_FILE mysql
#fi
